### PR TITLE
perf(db): optimize some tables to stored_only_fields to recrudesce me…

### PR DESCRIPTION
**Pull request by DEgITx**
…mory usage of big databases #152

### CODE REVIEW

**Comment by DEgITx** [comment]
@sanikolaev I added some modifications according suggestions, that keep ordering and selection keep working, so fields like hash, name in torrent cannot be converted, anyway, even you manticore developer keep look and review this PR, maybe you will notice any other potential thing to fix and imrove.

**Comment by sanikolaev** [comment]
> @sanikolaev I added some modifications according suggestions, that keep ordering and selection keep working, so fields like hash, name in torrent cannot be converted, anyway, even you manticore developer keep look and review this PR, maybe you will notice any other potential thing to fix and imrove. #152

Looks good to me in terms of Manticore config changes.

**Comment by DEgITx** [comment]
@sanikolaev , @tomatolog how to perform converting from attribute to stored filed
```
alter table torrents add column `ipv4` text stored;
```
doent's see a supported syntax, so is it possbile to do?

**Comment by tomatolog** [comment]
no you can not convert existed attribute into stored field for now. you need to reconfigure your index then repopulate it from scratch

**Pull request merged**
